[package]
name = "curvestuff"
type = "bin"
authors = [""]

[dependencies]
sort = {tag = "v0.2.0", git = "https://github.com/noir-lang/noir_sort"}
ripemd160 = { tag = "v0.0.2", git = "https://github.com/distributed-lab/noir-ripemd160" }
bignum = {tag = "v0.8.3", git = "https://github.com/noir-lang/noir-bignum"}
bigcurve = {tag = "v0.12.0", git = "https://github.com/noir-lang/noir_bigcurve"}
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
